name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-8-jdk python3-pip python3-setuptools git
          pip install --upgrade pip
          pip install buildozer cython

      - name: Initialize buildozer.spec
        run: |
          buildozer init
          sed -i 's/package.name = myapp/package.name = data_p2p_arbitraje/' buildozer.spec
          sed -i 's/package.domain = org.test/package.domain = org.carlos/' buildozer.spec
          sed -i 's/^# *requirements = python3,kivy/requirements = python3,kivy/' buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: data-p2p-arbitraje.apk
          path: bin/*.apk
